version: "3.8" # Remove this if you still get warnings about the version
services:
  ros_humble_abb_arm:
    image: ros_humble_abb_arm:latest
    container_name: abb_arm_container
    build:
      context: .
    command: /bin/bash # Start an interactive shell instead
    volumes:
      - ./abb_arm_ws:/home/rosuser/abb_arm_ws # Ensure the workspace is correctly mounted
      - /dev:/dev # Volume for accessing hardware devices
    environment:
      - ROS_DISTRO=humble
      - DISPLAY=host.docker.internal:0.0 # Environment variable for X11 display forwarding
    tty: true
    stdin_open: true
    privileged: true # Provides elevated privileges for hardware access
    network_mode: host # Use host network mode for better ROS communication
