version: "0.1" # Use a more recent version

services:
  ros:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - DISPLAY=host.docker.internal:0.0
    volumes:
      - /dev:/dev
    privileged: true
    tty: true # Enable TTY for interactive terminal
    stdin_open: true # Keep stdin open for interactive mode
    command: ["bash", "-c", "source /opt/ros/humble/setup.bash && exec bash"] # Source ROS setup
